In [1]:
#custom classifier on a wine dataset

In [3]:
#importing essentials

import numpy as np
from sklearn.datasets import load_wine

In [6]:
#retreiving data
data = load_wine()
data['DESCR']

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                     

In [7]:
X = data['data']
y = data['target']

In [11]:
#shape and other information

print(X.shape)


(178, 13)


In [12]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [13]:
#importing estimators

from sklearn.base import BaseEstimator, ClassifierMixin

In [15]:
#learning about counter
from collections import Counter

#printing y
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [20]:
c = Counter(y)
c

c.most_common(1)[0][0]

1

In [27]:
#defining and building a class

class MajorityClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self):
        pass
    
    def fit(self,X,y):
        c = Counter(y)
        self.mode_ = c.most_common(1)[0][0]
        self.fraction = np.array(list(c.values())) / X.shape[0]
        return self
    
    def predict(self,X):
        return self.mode_ * np.ones(X.shape[0])
        
    
    def predict_probability(self,X):
        return np.dot(np.ones((X.shape[0],1)), self.fraction.reshape(1,3))
        
    

In [28]:
mC = MajorityClassifier()

In [29]:
mC.fit(X,y)
mC.predict(X)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
mC.predict_probability(X)

array([[0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.33146067, 0.3988764 , 0.26966292],
       [0.

In [32]:
mC.predict_probability(X).shape

(178, 3)